default: &default
  adapter: mysql2
  host: localhost
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: instalist_api_development

test:
  <<: *default
  database: instalist_api_test

production:
  <<: *default
  database: instalist_api_production