login: &login
  adapter: mysql2
  host: localhost
  username: root
  encoding: utf8
  collation: utf8_general_ci

development:
  database: instalist_api_development
  <<: *login

test: &test
  database: instalist_api_test
  <<: *login

production:
  database: instalist_api_production
  <<: *login